package formularios;
import com.mysql.jdbc.Connection;
import conexion.conexionSQL;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author big_a
 */
public class CrearUsuarios extends javax.swing.JFrame {

   conexionSQL cc=new conexionSQL();
   Connection con=cc.conexion();
    
    
    public CrearUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nagregar = new javax.swing.JButton();
        Nusuario = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        Ncontraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        registro = new javax.swing.JLabel();
        blanco = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuArchivos = new javax.swing.JMenu();
        ItemClientes = new javax.swing.JMenuItem();
        ItemProductos = new javax.swing.JMenuItem();
        ItemUsuarios = new javax.swing.JMenuItem();
        ItemCambiarUsuario = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nagregar.setBackground(new java.awt.Color(255, 102, 153));
        Nagregar.setForeground(new java.awt.Color(255, 255, 255));
        Nagregar.setText("Agregar Usuario");
        Nagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NagregarActionPerformed(evt);
            }
        });
        jPanel1.add(Nagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 250, 30));
        jPanel1.add(Nusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 430, 40));

        usuario.setText("Usuario");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        Ncontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NcontraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(Ncontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 430, 40));

        jLabel1.setText("Contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, -1, -1));

        jLabel2.setText("Correo Electronico");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Crearusuario/logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 620, 270));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 430, 40));

        registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Crearusuario/fondo1.png"))); // NOI18N
        jPanel1.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 610, 730));

        blanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Crearusuario/fondo.jpg"))); // NOI18N
        jPanel1.add(blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 660, 720));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Crearusuario/content.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 730));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/menu.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Menu.add(jMenu1);

        MenuArchivos.setBorder(null);
        MenuArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/archivos.png"))); // NOI18N
        MenuArchivos.setText("Archivos");

        ItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/usuarios_1.png"))); // NOI18N
        ItemClientes.setText("Clientes");
        ItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemClientesActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemClientes);

        ItemProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        ItemProductos.setText("Productos");
        ItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemProductosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemProductos);

        ItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/clientes.png"))); // NOI18N
        ItemUsuarios.setText("Usuarios");
        ItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuariosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemUsuarios);

        ItemCambiarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/CambioUsuario.png"))); // NOI18N
        ItemCambiarUsuario.setText("Cambiar Usuario");
        ItemCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCambiarUsuarioActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemCambiarUsuario);

        Menu.add(MenuArchivos);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos1.png"))); // NOI18N
        MenuReportes.setText("Reportes");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/factura.png"))); // NOI18N
        jMenuItem3.setText("Nueva Factura");
        MenuReportes.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos.png"))); // NOI18N
        jMenuItem4.setText("Reporte Facturas");
        MenuReportes.add(jMenuItem4);

        Menu.add(MenuReportes);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/ayuda.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");
        Menu.add(MenuAyuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NagregarActionPerformed
        Agregarusuario(); // al momento de preciosar este boton, se realizara todos los pasos señalados de este metodo
        limpiar();
    }//GEN-LAST:event_NagregarActionPerformed

    private void ItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuariosActionPerformed
        CrearUsuarios form=new CrearUsuarios();
        form.setVisible(true);  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        this.dispose();
    }//GEN-LAST:event_ItemUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     principal form=new principal();
                        form.setVisible(true);  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
                        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCambiarUsuarioActionPerformed
        ModificaUsuario form=new ModificaUsuario(); // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
                        form.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_ItemCambiarUsuarioActionPerformed

    private void ItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemClientesActionPerformed

    private void ItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemProductosActionPerformed
       Inventario form= new Inventario();
       form.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_ItemProductosActionPerformed

    private void NcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NcontraseñaActionPerformed

    public void limpiar() {
        Nusuario.setText("");
        Ncontraseña.setText("");
        txtCorreo.setText("");
        
    }
    
    
    public void Agregarusuario(){
        String contraseña=String.valueOf(Ncontraseña.getPassword());  // creamos un String, y en ese string pasaremos los datos del dato que se introduzca en el textfield, y lo guardaremos
        String SQL="insert into usuarios (user,contraseña,correo) values(?,?,?)";   // Instrucción SQL para poder introducir los campos necesarios para crear un nuevo usuario
        
        
        try{
            PreparedStatement pst= con.prepareStatement(SQL);  // creamos un statement
            
            pst.setString(1, Nusuario.getText());  // creamos esta intruccion para poder introducir datos a nuestra tabla desde el textfield Nusuario
            pst.setString(2,contraseña);        // lo mismo pero desde la contraseña
            pst.setString(3,txtCorreo.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro exitoso"); // creamos esto para que en caso de que todo saliera bie, nos lanze un mensaje de confirmacion
                    
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error de Registro"+e.getMessage()); // y en caso de error nos lanzara este mensaje con el mensaje preciso de donde viene el error
        }
    }
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCambiarUsuario;
    private javax.swing.JMenuItem ItemClientes;
    private javax.swing.JMenuItem ItemProductos;
    private javax.swing.JMenuItem ItemUsuarios;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuArchivos;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JButton Nagregar;
    private javax.swing.JPasswordField Ncontraseña;
    private javax.swing.JTextField Nusuario;
    private javax.swing.JLabel blanco;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel registro;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
