/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import conexion.conexionSQL;
import java.sql.*;

import javax.swing.JOptionPane;
 

/**
 *
 * @author big_a
 */
public class Inventario extends javax.swing.JFrame {
 conexionSQL cc = new conexionSQL();
    Connection conectar;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int id = 0;
    com.mysql.jdbc.Connection con = cc.conexion();
    /**
     * Creates new form NewJFrame
     */
    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        listarproductos();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        Detalles_Productos = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        txtDescripción = new javax.swing.JTextField();
        Precio = new javax.swing.JLabel();
        IMAGEN = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        Precio1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        FOTO = new javax.swing.JLabel();
        fondoProducto = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuArchivos = new javax.swing.JMenu();
        ItemClientes = new javax.swing.JMenuItem();
        ItemProductos = new javax.swing.JMenuItem();
        ItemUsuarios = new javax.swing.JMenuItem();
        ItemCambiarUsuario = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Precio", "Imagen"
            }
        ));
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, 110));

        Detalles_Productos.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        Detalles_Productos.setText("MODIFICACIÓN DE PRODUCTOS");
        jPanel1.add(Detalles_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        Descripcion.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Descripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/description.png"))); // NOI18N
        Descripcion.setText("Descripción:");
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, -1, -1));
        jPanel1.add(txtDescripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 190, 30));

        Precio.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Precio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/peso.png"))); // NOI18N
        Precio.setText("Precio:");
        jPanel1.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, -1, -1));

        IMAGEN.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        IMAGEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/imagen.png"))); // NOI18N
        IMAGEN.setText("Imagen");
        jPanel1.add(IMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, -1, -1));
        jPanel1.add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 390, 190, 30));

        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/agregar.png"))); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 440, 130, 40));

        btnModificar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/Mostrar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 100, -1));

        btnNuevo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 610, 100, -1));

        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 610, 90, 40));

        btnActualizar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 670, 100, -1));

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/cancelar.png"))); // NOI18N
        btnCancelar.setText("Eliminar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 670, 90, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 110, 40));

        Precio1.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Precio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/codigo.png"))); // NOI18N
        Precio1.setText("Codigo");
        jPanel1.add(Precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, 190, 30));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 100, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, 190, 30));
        jPanel1.add(FOTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 330, 330));

        fondoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/color bg.png"))); // NOI18N
        jPanel1.add(fondoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 400, 330));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Inventario/fondo.png"))); // NOI18N
        jPanel1.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 810));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/menu.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Menu.add(jMenu1);

        MenuArchivos.setBorder(null);
        MenuArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/archivos.png"))); // NOI18N
        MenuArchivos.setText("Archivos");

        ItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/usuarios_1.png"))); // NOI18N
        ItemClientes.setText("Clientes");
        ItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemClientesActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemClientes);

        ItemProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        ItemProductos.setText("Productos");
        MenuArchivos.add(ItemProductos);

        ItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/clientes.png"))); // NOI18N
        ItemUsuarios.setText("Usuarios");
        ItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuariosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemUsuarios);

        ItemCambiarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/CambioUsuario.png"))); // NOI18N
        ItemCambiarUsuario.setText("Cambiar Usuario");
        ItemCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCambiarUsuarioActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemCambiarUsuario);

        Menu.add(MenuArchivos);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos1.png"))); // NOI18N
        MenuReportes.setText("Reportes");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/factura.png"))); // NOI18N
        jMenuItem3.setText("Nueva Factura");
        MenuReportes.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos.png"))); // NOI18N
        jMenuItem4.setText("Reporte Facturas");
        MenuReportes.add(jMenuItem4);

        Menu.add(MenuReportes);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/ayuda.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");
        Menu.add(MenuAyuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
     int fila = TablaDatos.getSelectedRow();
        if (fila >=0){
            txtID.setText(TablaDatos.getValueAt(fila,0).toString());
            txtCodigo.setText(TablaDatos.getValueAt(fila,1).toString());
            txtDescripción.setText(TablaDatos.getValueAt(fila,2).toString()); 
            txtPrecio.setText(TablaDatos.getValueAt(fila, 3).toString());
            txtImagen.setText(TablaDatos.getValueAt(fila, 4).toString());
        }
        else{
            JOptionPane.showMessageDialog(null,"Fila no Seleccionada");
        }       
    
      
           
 
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        AgregarProductos();
        limpiar();
        listarproductos();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        principal form=new principal();
        form.setVisible(true);  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClientesActionPerformed
          ClientesFrecuentes form= new ClientesFrecuentes();
       form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemClientesActionPerformed

    private void ItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuariosActionPerformed
        CrearUsuarios form=new CrearUsuarios();
        form.setVisible(true);  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        this.dispose();
    }//GEN-LAST:event_ItemUsuariosActionPerformed

    private void ItemCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCambiarUsuarioActionPerformed
        ModificaUsuario form=new ModificaUsuario(); // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemCambiarUsuarioActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
       JFileChooser archivo = new JFileChooser();
       int ventana = archivo.showOpenDialog(null);
       if(ventana == JFileChooser.APPROVE_OPTION){
           File file = archivo.getSelectedFile();
           txtImagen.setText(String.valueOf(file));
           
       Image foto= getToolkit().getImage(txtImagen.getText());
       foto = foto.getScaledInstance(250,250, Image.SCALE_DEFAULT);
       FOTO.setIcon(new ImageIcon(foto));
       }
    }//GEN-LAST:event_btnSeleccionarActionPerformed
public void EliminarDatos() {
        int filaSeleccionada = TablaDatos.getSelectedRow();       // convertiremos en un int  la fila seleccionada de nuestra tabla
        int m=JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar este usuario?","Registro",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(m==JOptionPane.YES_NO_OPTION){
        try {
            String SQL = "delete from inventario where ID=" + TablaDatos.getValueAt(filaSeleccionada, 0); // llenamos la siguiente intruccion SQL que nos permitirá eliminar el usuario que queramos 
            Statement st = con.createStatement();

            int n = st.executeUpdate(SQL);

            if (n >= 0) {
                JOptionPane.showMessageDialog(null, "Registro Eliminado");  // en caso de que la eliminacion haya sido correcta. nos lanzara el siguiente mensaje
                limpiarTabla(model);
                listarproductos();
            }
         } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar Registro" + e.getMessage()); // en caso contrari de que este no funcionara, nos lanzara este siguiente mensaje
        }

        }}


   public void limpiar() {
        txtCodigo.setText("");
        txtDescripción.setText("");
        txtPrecio.setText("");
        txtImagen.setText("");
    }
   public void limpiarTabla(DefaultTableModel model) {
        for (int i = 0; i <= TablaDatos.getRowCount(); i++) {
            model.removeRow(i);
            i = i - 1;
        }
    }
    
 public void AgregarProductos(){
         
     
     String SQL="insert into inventario (codigo,Precio,imagen) values(?,?,?,?)";   // Instrucción SQL para poder introducir los campos necesarios para crear un nuevo usuario   
        try{
            PreparedStatement pst= con.prepareStatement(SQL);  // creamos un statement
            
            pst.setString(1, txtCodigo.getText());  // creamos esta intruccion para poder introducir datos a nuestra tabla desde el textfield Nusuario
            pst.setString(2,txtPrecio.getText());        // lo mismo pero desde la contraseña
            pst.setString(3,txtDescripción.getText());
            pst.setString(4,txtImagen());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro exitoso"); // creamos esto para que en caso de que todo saliera bie, nos lanze un mensaje de confirmacion
                    
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error de Registro"+e.getMessage()); // y en caso de error nos lanzara este mensaje con el mensaje preciso de donde viene el error
        }
    }

    public void listarproductos() {
        String sql = "select * from inventario";
        try {
            con = cc.conexion();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] inventario = new Object[5];
            model = (DefaultTableModel) TablaDatos.getModel();
            while (rs.next()) {
                inventario[0] = rs.getInt("ID");
                inventario[1] = rs.getString("codigo");
                inventario[2] = rs.getString("nombre");
                inventario[3] = rs.getString("Precio");
                inventario[4] = rs.getString("imagen");
                model.addRow(inventario);
            }
            TablaDatos.setModel(model);

        } catch (Exception e) {
        }
    }
    
     
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        EliminarDatos();  // Esto nos permitirá eliminar los datos de algun usuario al hacer click en el boton de "Eliminar DAtos"
       
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtPrecio.setText("");
        txtCodigo.setText("");
        txtDescripción.setText("");
        txtImagen.setText("");
        txtID.setText("");
        FOTO.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Detalles_Productos;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel FOTO;
    private javax.swing.JLabel IMAGEN;
    private javax.swing.JMenuItem ItemCambiarUsuario;
    private javax.swing.JMenuItem ItemClientes;
    private javax.swing.JMenuItem ItemProductos;
    private javax.swing.JMenuItem ItemUsuarios;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuArchivos;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Precio1;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel fondoProducto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripción;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private String txtImagen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
