/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.conexionSQL;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author big_a
 */
public class ModificaUsuario extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection conectar;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int id = 0;
    com.mysql.jdbc.Connection con = cc.conexion();

    /**
     * Creates new form ModificaUsuario
     */
    public ModificaUsuario() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcontraN = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        botonBuscar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        txtnombreN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuArchivos = new javax.swing.JMenu();
        ItemClientes = new javax.swing.JMenuItem();
        ItemProductos = new javax.swing.JMenuItem();
        ItemUsuarios = new javax.swing.JMenuItem();
        ItemCambiarUsuario = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarContraseña/monitor with profile icon 1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 260, 260));

        txtcontraN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraNActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontraN, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 350, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, -1, -1));

        BotonActualizar.setBackground(new java.awt.Color(255, 102, 255));
        BotonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BotonActualizar.setText("Cambiar Usuario");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 610, -1, -1));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Contraseña"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, 120));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        BotonEliminar.setBackground(new java.awt.Color(153, 0, 51));
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar Usuario");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 610, -1, -1));
        jPanel1.add(txtnombreN, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 350, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ACTUALIZACION DE USUARIOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 630, 50));

        jLabel6.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Busqueda de Usuarios");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, -1, -1));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 350, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarUsuario/checked-user-xxl.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 250, 260));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarUsuario/Dashboard Login.jpg"))); // NOI18N
        Fondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1280, 720));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/menu.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Menu.add(jMenu1);

        MenuArchivos.setBorder(null);
        MenuArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/archivos.png"))); // NOI18N
        MenuArchivos.setText("Archivos");

        ItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/usuarios_1.png"))); // NOI18N
        ItemClientes.setText("Clientes");
        MenuArchivos.add(ItemClientes);

        ItemProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        ItemProductos.setText("Productos");
        ItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemProductosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemProductos);

        ItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/clientes.png"))); // NOI18N
        ItemUsuarios.setText("Usuarios");
        ItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuariosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemUsuarios);

        ItemCambiarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/CambioUsuario.png"))); // NOI18N
        ItemCambiarUsuario.setText("Cambiar Usuario");
        MenuArchivos.add(ItemCambiarUsuario);

        Menu.add(MenuArchivos);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos1.png"))); // NOI18N
        MenuReportes.setText("Reportes");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/factura.png"))); // NOI18N
        jMenuItem3.setText("Nueva Factura");
        MenuReportes.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos.png"))); // NOI18N
        jMenuItem4.setText("Reporte Facturas");
        MenuReportes.add(jMenuItem4);

        Menu.add(MenuReportes);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/ayuda.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");
        Menu.add(MenuAyuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcontraNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraNActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        Modificarusuario();
        listar();


    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        principal form = new principal();  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuariosActionPerformed
        CrearUsuarios form = new CrearUsuarios();  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemUsuariosActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
     /*   String nombre = txtnombreN.getText();  // Creamos un String nombre y lo agregamos a nuestro textfield que tenda el nombre del usuario
        String where = "";
        if (!"".equals(nombre)) {
            where = "WHERE user = '" + nombre + "'";     // Creamos esta condicion en SQL para que este puede localizar usuarios por nombre dentro de nuestra tabla 
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/proyecto1", "root", "Teccnoyil1@");  // Conectividad con nuestra base de datos con las credenciales Correspondientes
            Statement stm = conexion.createStatement();
            ResultSet rst = stm.executeQuery("SELECT * FROM usuarios " + where);
            ResultSetMetaData rsMd = rst.getMetaData();
            int numcolumnas = rsMd.getColumnCount();
            DefaultTableModel modelo = new DefaultTableModel();
            this.TablaDatos.setModel(modelo);
            for (int x = 1; x <= numcolumnas; x++) {
                modelo.addColumn(rsMd.getColumnLabel(x)); // esto permitirá visualizar los datos de nuesta tabla, en un tabla grafica
            }
            while (rst.next()) {
                Object[] fila = new Object[numcolumnas];
                for (int y = 0; y < numcolumnas; y++) {
                    fila[y] = rst.getObject(y + 1);
                }

                modelo.addRow(fila);
            }
        } catch (ClassNotFoundException ce) {

            ce.printStackTrace();

        } catch (SQLException se) {

            se.printStackTrace();
        }*/


    }//GEN-LAST:event_botonBuscarActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        /*int filaSeleccionada=TablaDatos.rowAtPoint(evt.getPoint());              // esto nor permitirá obtener el dato del usuario que queramos con tan solo hacer click en la tabla
       txtID.setText(TablaDatos.getValueAt(filaSeleccionada, 0).toString());
       txtnombreN.setText(TablaDatos.getValueAt(filaSeleccionada,1).toString()); // y a su vez se llenarán de manera automatica en los textfields
       txtcontraN.setText(TablaDatos.getValueAt(filaSeleccionada,2).toString()); */

        int fila = TablaDatos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "usuario no seleccionado");
        } else {
            int id = Integer.parseInt((String) TablaDatos.getValueAt(fila, 0).toString());
            String nombreN = (String) TablaDatos.getValueAt(fila, 1);
            String contraN = (String) TablaDatos.getValueAt(fila, 2);
            txtID.setText("" + id);
            txtnombreN.setText(nombreN);
            txtcontraN.setText(contraN);
        }


    }//GEN-LAST:event_TablaDatosMouseClicked

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        EliminarDatos();  // Esto nos permitirá eliminar los datos de algun usuario al hacer click en el boton de "Eliminar DAtos"
        listar();
        nuevo();
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void ItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemProductosActionPerformed
       Inventario form= new Inventario();
       form.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_ItemProductosActionPerformed

    public void EliminarDatos() {
        int filaSeleccionada = TablaDatos.getSelectedRow();       // convertiremos en un int  la fila seleccionada de nuestra tabla

        try {
            String SQL = "delete from usuarios where ID=" + TablaDatos.getValueAt(filaSeleccionada, 0); // llenamos la siguiente intruccion SQL que nos permitirá eliminar el usuario que queramos 
            Statement st = con.createStatement();

            int n = st.executeUpdate(SQL);

            if (n >= 0) {
                JOptionPane.showMessageDialog(null, "Registro Eliminado");  // en caso de que la eliminacion haya sido correcta. nos lanzara el siguiente mensaje
                limpiarTabla(model);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar Registro" + e.getMessage()); // en caso contrari de que este no funcionara, nos lanzara este siguiente mensaje
        }

    }

    

    public void listar() {
        String sql = "select * from usuarios";
        try {
            con = cc.conexion();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] usuarios = new Object[3];
            model = (DefaultTableModel) TablaDatos.getModel();
            while (rs.next()) {
                usuarios[0] = rs.getInt("ID");
                usuarios[1] = rs.getString("user");
                usuarios[2] = rs.getString("contraseña");
                model.addRow(usuarios);
            }
            TablaDatos.setModel(model);

        } catch (Exception e) {
        }
    }

    public void Actualizar() {
        limpiarTabla(model);
        listar();
    }

    public void Modificarusuario() {
        String id = txtID.getText();
        String nombreN = txtnombreN.getText();
        char[] contraN = txtcontraN.getPassword();
        String SQL = "UPDATE usuarios set user='" + nombreN + "',contraseña='" + contraN + "' where ID=" + id;
         try {
              if (nombreN.equals("") || contraN.equals("")) {
               con = cc.conexion();
            st = con.createStatement();
            rs = st.executeQuery(SQL);
             JOptionPane.showMessageDialog(null, "usuario Actualizado");
             limpiarTabla(model);
        /*String SQL="UPDATE usuarios set user=?, contraseña=?, where ID=? ";*/
        } else {
            JOptionPane.showMessageDialog(null, "Error!!!!");
              }
            } catch (Exception e) {
            }
        }
    

   public void nuevo() {
        txtID.setText("");
        txtnombreN.setText("");
        txtcontraN.setText("");
        txtID.requestFocus();
    }
   public void limpiarTabla(DefaultTableModel model) {
        for (int i = 0; i <= TablaDatos.getRowCount(); i++) {
            model.removeRow(i);
            i = i - 1;
        }
    }
    
    
    
    
    
    
    

    /*try{
               
        int filaSeleccionada=TablaDatos.getSelectedRow();
        String dao=(String)TablaDatos.getValueAt(filaSeleccionada,0);
         
        String SQL="UPDATE usuarios set user=?, contraseña=?, where ID=? ";
             
             
        PreparedStatement pst= con.prepareStatement(SQL);
             pst.setString(1, txtnombreN.getText().trim());  
            String pass=String.valueOf(txtcontraN.getPassword());                            
            pst.setString(2,pass);
            pst.setString(3,dao);
            
        
            
            
            
            
            
            
           int n= pst.executeUpdate();
           
           if (n>=0){
            JOptionPane.showMessageDialog(null,"Cambio de Usuario exitoso");

           }
            
                    
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al Cambiar el Usuario"+e.getMessage());
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenuItem ItemCambiarUsuario;
    private javax.swing.JMenuItem ItemClientes;
    private javax.swing.JMenuItem ItemProductos;
    private javax.swing.JMenuItem ItemUsuarios;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuArchivos;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtcontraN;
    private javax.swing.JTextField txtnombreN;
    // End of variables declaration//GEN-END:variables
}
