/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.*;
import conexion.conexionSQL;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author big_a
 */
public class ModificaUsuario extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection conectar;
    DefaultTableModel model;
    Statement st = null;
    ResultSet rs;
    int id = 0;
    com.mysql.jdbc.Connection con = cc.conexion();

    /**
     * Creates new form ModificaUsuario
     */
    public ModificaUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcontraN = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        BotonActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        txtnombreN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuArchivos = new javax.swing.JMenu();
        ItemClientes = new javax.swing.JMenuItem();
        ItemProductos = new javax.swing.JMenuItem();
        ItemUsuarios = new javax.swing.JMenuItem();
        ItemCambiarUsuario = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcontraN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraNActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontraN, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 510, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, -1, -1));

        BotonActualizar.setFont(new java.awt.Font("Roboto", 3, 11)); // NOI18N
        BotonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarUsuario/update.png"))); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 120, 40));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Contraseña", "Correo"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 120));

        btnLimpiar.setFont(new java.awt.Font("Roboto", 3, 11)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarUsuario/borrar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, 120, 40));

        BotonEliminar.setFont(new java.awt.Font("Roboto", 3, 11)); // NOI18N
        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarUsuario/Eliminar.png"))); // NOI18N
        BotonEliminar.setText("Eliminar  ");
        BotonEliminar.setBorder(null);
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 120, 40));
        jPanel1.add(txtnombreN, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 520, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Busqueda de Usuarios");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, -1, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 520, 30));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 190, 30));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarUsuario/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_CambiarUsuario/Sign Up.png"))); // NOI18N
        Fondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/menu.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Menu.add(jMenu1);

        MenuArchivos.setBorder(null);
        MenuArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/archivos.png"))); // NOI18N
        MenuArchivos.setText("Archivos");

        ItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/usuarios_1.png"))); // NOI18N
        ItemClientes.setText("Clientes");
        ItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemClientesActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemClientes);

        ItemProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        ItemProductos.setText("Productos");
        ItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemProductosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemProductos);

        ItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/clientes.png"))); // NOI18N
        ItemUsuarios.setText("Usuarios");
        ItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuariosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemUsuarios);

        ItemCambiarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/CambioUsuario.png"))); // NOI18N
        ItemCambiarUsuario.setText("Cambiar Usuario");
        MenuArchivos.add(ItemCambiarUsuario);

        Menu.add(MenuArchivos);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos1.png"))); // NOI18N
        MenuReportes.setText("Reportes");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/factura.png"))); // NOI18N
        jMenuItem3.setText("Nueva Factura");
        MenuReportes.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos.png"))); // NOI18N
        jMenuItem4.setText("Reporte Facturas");
        MenuReportes.add(jMenuItem4);

        Menu.add(MenuReportes);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/ayuda.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");
        Menu.add(MenuAyuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcontraNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraNActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
Modificarusuario();        
      // limpiar();
      //  listar();

/*try{
    String contraseña=String.valueOf(txtcontraN.getPassword());

    String sql="Update usuarios set user=?, contraseña=?, correo=? "+
            "where ID=?";
    int fila=TablaDatos.getSelectedRow();
    String dao=(String)TablaDatos.getValueAt(fila,0);
    PreparedStatement ps=conectar.prepareCall(sql);
    ps.setString(1,txtnombreN.getText());
    ps.setString(2,contraseña);
    ps.setString(3,txtCorreo.getText());

     //BasedeDatos

   ps.setString(4,dao);//la llamada sql se muestra en la tabla

    int n=ps.executeUpdate();
    if(n>0){
        limpiar();
        listar();
        JOptionPane.showMessageDialog(null, "datos modificados");
       
    }
}catch (Exception e){
    JOptionPane.showMessageDialog(null, "error"+ e.getMessage());
}*/
         
      


    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        principal form = new principal();  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuariosActionPerformed
        CrearUsuarios form = new CrearUsuarios();  // Con esto nor permitirá acceder a otra pestañana al hacer click en el item
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemUsuariosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        
  
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
       


    }//GEN-LAST:event_TablaDatosMouseClicked

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        EliminarDatos();  // Esto nos permitirá eliminar los datos de algun usuario al hacer click en el boton de "Eliminar DAtos"
        listar();
        limpiar();
        
       
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void ItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemProductosActionPerformed
       Inventario form= new Inventario();
       form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemProductosActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        int fila = TablaDatos.getSelectedRow();
        if (fila >=0){
            txtID.setText(TablaDatos.getValueAt(fila,0).toString());
            txtnombreN.setText(TablaDatos.getValueAt(fila,1).toString());
            txtcontraN.setText(TablaDatos.getValueAt(fila,2).toString()); 
            txtCorreo.setText(TablaDatos.getValueAt(fila, 3).toString());

        }
        else{
            JOptionPane.showMessageDialog(null,"Fila no Seleccionada");
        }       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void ItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClientesActionPerformed
        ClientesFrecuentes form= new ClientesFrecuentes();
       form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemClientesActionPerformed

    public void EliminarDatos() {
        int filaSeleccionada = TablaDatos.getSelectedRow();       // convertiremos en un int  la fila seleccionada de nuestra tabla
        int m=JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar este usuario?","Registro",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(m==JOptionPane.YES_NO_OPTION){
        try {
            String SQL = "delete from usuarios where ID=" + TablaDatos.getValueAt(filaSeleccionada, 0); // llenamos la siguiente intruccion SQL que nos permitirá eliminar el usuario que queramos 
            Statement st = con.createStatement();

            int n = st.executeUpdate(SQL);

            if (n >= 0) {
                JOptionPane.showMessageDialog(null, "Registro Eliminado");  // en caso de que la eliminacion haya sido correcta. nos lanzara el siguiente mensaje
                limpiarTabla(model);
            }
         } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar Registro" + e.getMessage()); // en caso contrari de que este no funcionara, nos lanzara este siguiente mensaje
        }

        }}

    

    public void listar() {
        String sql = "select * from usuarios";
        try {
            con = cc.conexion();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] usuarios = new Object[4];
            model = (DefaultTableModel) TablaDatos.getModel();
            while (rs.next()) {
                usuarios[0] = rs.getInt("ID");
                usuarios[1] = rs.getString("user");
                usuarios[2] = rs.getString("contraseña");
                usuarios[3] = rs.getString("correo");
                model.addRow(usuarios);
            }
            TablaDatos.setModel(model);

        } catch (Exception e) {
        }
    }

    public void Actualizar() {
        limpiarTabla(model);
        listar();
    }

     public void Modificarusuario() {
            /*String id = txtID.getText().trim();
            String nombre = txtnombreN.getText().trim();
            String contraN=String.valueOf(txtcontraN.getPassword());
            String correo = txtCorreo.getText().trim();
      try {
            PreparedStatement ps = (PreparedStatement) conectar .prepareStatement("Update usuarios set user=?, contraseña=?, correo=? wbere ID=?");
            
            ps.setString(0,id);
              ps.setString(1,nombre);
                ps.setString(2,contraN);
                  ps.setString(3, correo);
                  
                    //SET user='"+txtnombreN.getText()+",contraseña='"+txtcontraN.getText().trim()+",correo='"+txtCorreo.getText()
            //+" WHERE ID="+txtID.getText()+";");
           // ps.executeUpdate();
             int n=ps.executeUpdate();
    if(n>0){
        limpiar();
        listar();
        JOptionPane.showMessageDialog(null, "datos modificados");
     
    }
           // JOptionPane.showMessageDialog(null, "Datos Actualizados");
        } catch (SQLException ex) {
            Logger.getLogger(ModificaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null,"Error al Cambiar el Usuario"+ex.getMessage());

        }   */
         
         
         
         
try{
   // String contraseña=String.valueOf(txtcontraN.getPassword());

    String sql="Update usuarios set user=?, contraseña=?, correo=? "+
            "where ID=?";
     int fila=TablaDatos.getSelectedRow();
    String dao=(String)TablaDatos.getValueAt(fila,0);
    PreparedStatement ps=conectar.prepareCall(sql);
    ps.setString(1,txtID.getText());
    ps.setString(2,txtnombreN.getText());
    ps.setString(3,txtcontraN.getText());
    ps.setString(4,txtCorreo.getText());

     //BasedeDatos

   ps.setString(5,dao);//la llamada sql se muestra en la tabla

    int n=ps.executeUpdate();
    if(n>0){
        limpiar();
        listar();
        JOptionPane.showMessageDialog(null, "datos modificados");  
     
    }
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, "error"+ e.getMessage());

    }

     }

   public void limpiar() {
        txtCorreo.setText("");
        txtnombreN.setText("");
        txtcontraN.setText("");
        txtID.setText("");
        txtCorreo.requestFocus();
    }
   
   
   public void limpiarTabla(DefaultTableModel model) {
        for (int i = 0; i <= TablaDatos.getRowCount(); i++) {
            model.removeRow(i);
            i = i - 1;
        }
    }
    
    
    
    
    
    
    

    /*try{
               
        int filaSeleccionada=TablaDatos.getSelectedRow();
        String dao=(String)TablaDatos.getValueAt(filaSeleccionada,0);
         
        String SQL="UPDATE usuarios set user=?, contraseña=?, where ID=? ";
             
             
        PreparedStatement pst= con.prepareStatement(SQL);
             pst.setString(1, txtnombreN.getText().trim());  
            String pass=String.valueOf(txtcontraN.getPassword());                            
            pst.setString(2,pass);
            pst.setString(3,dao);
            
        
            
            
            
            
            
            
           int n= pst.executeUpdate();
           
           if (n>=0){
            JOptionPane.showMessageDialog(null,"Cambio de Usuario exitoso");

           }
            
                    
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al Cambiar el Usuario"+e.getMessage());
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenuItem ItemCambiarUsuario;
    private javax.swing.JMenuItem ItemClientes;
    private javax.swing.JMenuItem ItemProductos;
    private javax.swing.JMenuItem ItemUsuarios;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuArchivos;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtcontraN;
    private javax.swing.JTextField txtnombreN;
    // End of variables declaration//GEN-END:variables
}
