package formularios;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author big_a
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuArchivos = new javax.swing.JMenu();
        ItemClientes = new javax.swing.JMenuItem();
        ItemProductos = new javax.swing.JMenuItem();
        ItemUsuarios = new javax.swing.JMenuItem();
        ItemCambiarUsuario = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/Thumbnail.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        MenuArchivos.setBorder(null);
        MenuArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/archivos.png"))); // NOI18N
        MenuArchivos.setText("Archivos");

        ItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/usuarios_1.png"))); // NOI18N
        ItemClientes.setText("Clientes");
        ItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemClientesActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemClientes);

        ItemProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/inventario.png"))); // NOI18N
        ItemProductos.setText("Productos");
        MenuArchivos.add(ItemProductos);

        ItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/clientes.png"))); // NOI18N
        ItemUsuarios.setText("Usuarios");
        ItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuariosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemUsuarios);

        ItemCambiarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/CambioUsuario.png"))); // NOI18N
        ItemCambiarUsuario.setText("Cambiar Usuario");
        ItemCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCambiarUsuarioActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemCambiarUsuario);

        jMenuBar2.add(MenuArchivos);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos1.png"))); // NOI18N
        MenuReportes.setText("Reportes");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/factura.png"))); // NOI18N
        jMenuItem3.setText("Nueva Factura");
        MenuReportes.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/movimientos.png"))); // NOI18N
        jMenuItem4.setText("Reporte Facturas");
        MenuReportes.add(jMenuItem4);

        jMenuBar2.add(MenuReportes);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contenido_Principal/ayuda.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");
        jMenuBar2.add(MenuAyuda);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuariosActionPerformed
        CrearUsuarios form=new CrearUsuarios();   // esto nos permitirá acceder a la ventana "crear Usuarios" al momento al hacer click en ese item
                        form.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_ItemUsuariosActionPerformed

    private void ItemCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCambiarUsuarioActionPerformed
        ModificaUsuario form=new ModificaUsuario();   // esto nos permitirá acceder a la ventana "ModificaUsuario"  al momento al hacer click en ese item
                        form.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_ItemCambiarUsuarioActionPerformed

    private void ItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClientesActionPerformed
       ClientesFrecuentes form= new ClientesFrecuentes();
       form.setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_ItemClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenuItem ItemCambiarUsuario;
    private javax.swing.JMenuItem ItemClientes;
    private javax.swing.JMenuItem ItemProductos;
    private javax.swing.JMenuItem ItemUsuarios;
    private javax.swing.JMenu MenuArchivos;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
